version: '3'
services:
  postgres:
    networks:
      - my_network
    image: postgres:latest
    environment:
      POSTGRES_DB: time_manager_api_with_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  elixir_app:
    networks:
      - my_network
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: time_manager_api_with_auth
      DB_HOST: postgres
      DB_PORT: 5432
      DB_POOL_SIZE: 15

networks:
  my_network:

volumes:
  pgdata: